"""Render or verify the nine submission figures using frozen plot inputs only."""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import statistics
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
DATA = 'dissertation_artifacts/data/'
FIGURES = [
    ('4.1', 'eurusd_nonparametric_kernel.pdf', 'render_eurusd_kernel_comparison.py',
     'Hawkes excitation kernels for EUR/USD',
     [DATA+'eurusd_konark_cls_kernel.json', DATA+'plot_inputs/eurusd_em_parameters.json'],
     'Conditional least squares and converged EM estimates from the same 97,952 EUR/USD events. '
     'The upper panels show the full fitted branching matrices. Each cell gives the expected number of direct events of the row type generated by one event of the column type under the fitted model. '
     'CLS integrates over its fitted 0-500 second support; EM integrates its exponential kernels to infinity. '
     'The spectral radii are 0.9784 and 0.9373. '
     'The lower panels show the first ten seconds of bid-up to bid-down excitation and bid-up to ask-up excitation: respectively the strongest shared off-diagonal interaction and the largest remaining difference in integrated strength. '
     'The blue steps show the saved CLS bins and the dashed orange lines the saved EM kernels.'),
    ('4.2', 'eurusd_layer1_em_residual_qq.pdf', 'render_eurusd_layer1_em_residual.py',
     'Time-rescaling residuals of the EUR/USD EM fit',
     [DATA+'eurusd_layer1_em_residual_plot_data.npz'],
     'Pooled fitted-compensator increments against unit-exponential quantiles. '
     'The central 99.9% is shown on linear axes and the complete range on logarithmic axes.'),
    ('4.3', 'eurusd_fano_forward_validation.pdf', 'render_eurusd_fano_validation.py',
     'Empirical and simulated count dispersion',
     [DATA+'plot_inputs/eurusd_empirical_fano.json', DATA+'plot_inputs/eurusd_simulated_fano.json'],
     'Empirical Fano factors compared with the median and minimum-maximum range across 30 stored fitted-model simulations. '
     'The empirical value lies below all simulations at 1, 10 and 60 seconds and inside their range at 300 seconds.'),
    ('4.4', 'd2_latent_book_inference.pdf', 'render_d2_latent_book_inference.py',
     'Latent-book projection and recovery under weak pressure',
     [DATA+'d2_latent_book_calibration_summary.json', DATA+'d2_latent_book_posterior_plot_data.json'],
     'Native-event counts before and after projection, recovery scores for both streams, and the projected-stream full-sequence higher-rate-state probabilities inside and outside the known pressure periods.'),
    ('4.5', 'd2_regime_detectability_sweep.pdf', 'render_d2_regime_detectability_sweep.py',
     'Stronger pressure is easier to detect',
     [DATA+'d2_regime_detectability_sweep.json'],
     'Recovery before and after projection across 30 pressure settings. '
     'The left panel introduces market orders and in-spread limit orders; the right also introduces top-of-book limit orders and cancellations. '
     'The affected book side alternates between successive pressure periods. '
     'The horizontal values are the total rate multiplier m=1+delta_p. '
     'Marker shape gives the fraction of time under pressure; open and filled markers distinguish latent and projected streams. '
     'Each setting contains one simulation. The dashed line marks the F1=0.7 evaluation criterion.'),
    ('5.1', 'recovery_hmm_posterior.pdf', 'render_recovery_hmm_posterior.py',
     'Recovering a known directional-pressure period',
     [DATA+'recovery_hmm_meta_order_smoke.json', 'configs/meta_order_smoke.json'],
     None),
    ('5.2', 'recovery_method_comparison.pdf', 'render_recovery_method_comparison.py',
     'Recovery accuracy across 50 controlled simulations',
     [DATA+'recovery_hmm_meta_order_smoke.json', DATA+'recovery_summary.csv'],
     None),
    ('6.1', 'layer3_d1_markout_distribution.pdf', 'render_layer3_d1_markout_distribution.py',
     'Post-fill movement and fill proportions',
     [DATA+'layer3_d1_skew_markout_comparison.json'],
     None),
    ('6.2', 'layer3_d1_skew_frontier.pdf', 'render_layer3_d1_skew_frontier.py',
     'Execution-value frontier',
     [DATA+'layer3_d1_skew_frontier.json'],
     'Thirty matched simulations at seven posterior-sensitivity settings. '
     'The upper panel shows fill proportions relative to each seed\'s s=0 baseline, with medians; the lower shows changes from s=0 in mean absolute five-second movement in ticks, with equal-seed means. '
     'The horizontal references mark half of baseline fills and zero movement change.'),
]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def result_captions():
    """Describe the saved results without freezing earlier numerical outcomes."""
    hmm = json.loads((REPO / DATA / 'recovery_hmm_meta_order_smoke.json').read_text())
    records = sorted(hmm['per_seed'], key=lambda row: int(row['seed_dir'].rsplit('_', 1)[1]))
    seeds = [int(row['seed_dir'].rsplit('_', 1)[1]) for row in records]
    if seeds != list(range(1, 51)):
        raise ValueError('HMM captions require unique seeds 1 through 50')
    hmm_f1 = [float(row['f1']) for row in records]
    with (REPO / DATA / 'recovery_summary.csv').open(newline='') as handle:
        threshold_rows = list(csv.DictReader(handle))
    threshold_by_seed = {int(row['seed']): float(row['f1']) for row in threshold_rows}
    if len(threshold_rows) != 50 or set(threshold_by_seed) != set(seeds):
        raise ValueError('Caption inputs must describe the same 50 simulation seeds')
    threshold_f1 = [threshold_by_seed[seed] for seed in seeds]
    if any(not math.isfinite(value) or not 0.0 <= value <= 1.0 for value in hmm_f1 + threshold_f1):
        raise ValueError('Caption inputs contain an invalid F1 score')
    for values, aggregate in ((hmm_f1, 'hmm_aggregate'), (threshold_f1, 'threshold_aggregate')):
        if not math.isclose(statistics.mean(values), float(hmm[aggregate]['f1_mean']), abs_tol=1e-14, rel_tol=0.0):
            raise ValueError('Caption means do not reproduce the saved aggregate')
    median_f1 = statistics.median(hmm_f1)
    representative = min(range(len(records)), key=lambda index: abs(hmm_f1[index] - median_f1))
    # Match the plot: treat differences <= 1e-12 as numerical ties.
    paired = list(zip(hmm_f1, threshold_f1))
    n_higher = sum(h > t and not math.isclose(h, t, abs_tol=1e-12, rel_tol=0.0) for h, t in paired)
    n_lower = sum(h < t and not math.isclose(h, t, abs_tol=1e-12, rel_tol=0.0) for h, t in paired)
    n_equal = len(seeds) - n_higher - n_lower

    markout = json.loads((REPO / DATA / 'layer3_d1_skew_markout_comparison.json').read_text())
    markout_rows = markout['per_seed']
    if sorted(int(row['seed']) for row in markout_rows) != list(range(1, 31)):
        raise ValueError('Markout captions require unique seeds 1 through 30')
    counts = []
    for arm in ('a', 'b'):
        count = 0
        for row in markout_rows:
            observed_count = len(row[f'per_fill_signed_markout_5s_episode_{arm}'])
            if observed_count != int(row[f'aggregates_episode_{arm}']['5.0']['n_fills']):
                raise ValueError('Caption fill count does not match the saved aggregate')
            count += observed_count
        counts.append(count)
    return {
        '5.1': (
            'Full-sequence probability of the fitted higher-rate activity state on the '
            f'deterministic median-F1 example (seed {seeds[representative]}), with the known '
            'directional-pressure period shaded. The state is identified by fitted activity rate; '
            'the displayed probability uses the complete sequence.'
        ),
        '5.2': (
            f'Paired F1 scores for the rate-and-imbalance threshold method and HMM on the same {len(seeds)} simulation seeds. '
            f'The HMM scores higher on {n_higher} seeds, lower on {n_lower}, and ties on {n_equal}; '
            f'the means are {statistics.mean(threshold_f1):.3f} and {statistics.mean(hmm_f1):.3f}.'
        ),
        '6.1': (
            f'The cumulative curves pool {counts[0]:,} and {counts[1]:,} valid post-fill records at s=0 and s=1. '
            'At movement x, the curve gives the percentage of valid fills with absolute five-second movement no greater than x. '
            'The right panel shows fills as a percentage of bid- and ask-side quote opportunities over each complete 600-second simulation. '
            'Thirty matched simulations are shown. Absolute movement measures magnitude; signed markout retains economic direction.'
        ),
    }


def entries():
    rows = []
    captions = result_captions()
    for number, name, renderer, title, inputs, caption in FIGURES:
        paths = [REPO / s for s in inputs]
        if any(not p.resolve().is_relative_to(REPO.resolve()) for p in paths):
            raise ValueError('Submission inputs must be repository-relative')
        rows.append(dict(
            figure=number, path=str((HERE/name).relative_to(REPO)), title=title,
            generator=str((HERE/renderer).relative_to(REPO)), source_data=inputs,
            source_sha256={s:digest(REPO/s) for s in inputs},
            generator_sha256=digest(HERE/renderer), pdf_sha256=digest(HERE/name),
            caption=captions.get(number, caption),
        ))
    return {'scope':'Final MSc submission figures; plot-only rendering from frozen results', 'figures':rows}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--check', action='store_true', help='Verify hashes without writing')
    group.add_argument('--manifest-only', action='store_true', help='Record already-rendered figures')
    args = parser.parse_args()
    path = HERE/'figure_manifest.json'
    if args.check:
        if json.loads(path.read_text()) != entries():
            raise SystemExit('Submission manifest differs from the current inputs, renderers or PDFs')
        print('Verified all nine submission figures, source hashes and renderer hashes')
        return
    if not args.manifest_only:
        for _, _, renderer, _, _, _ in FIGURES:
            subprocess.run([sys.executable, str(HERE/renderer)], check=True)
    path.write_text(json.dumps(entries(), indent=2)+'\n')
    print('Recorded nine submission figures in figure_manifest.json')


if __name__ == '__main__':
    main()
